openapi: 3.0.0
info:
  title: Minimal OpenAPI Spec
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /hello:
    get:
      operationId: sayHello
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: { "message": "Hello, world!" }
