openapi: 3.0.0
info:
  title: Minimal OpenAPI Spec for Saying Goodbye
  version: 1.0.0
servers:
    - url: http://localhost:8081
paths:
  /goodbye:
    get:
      operationId: sayGoodbye
      responses:
        '200':
          description: OK
          content:
            application/json:
              example: { "message": "Goodbye, world!" }
