openapi: 3.0.0
info:
  title: Teapot API
  version: 1.0.0
servers:
  - url: http://localhost:4040
# This script is executed when the spec is loaded.
# You can use it to specify global variables and functions that are available to all scripts.
x-sim-script: |
  var status = 418
paths:
  /teapot:
    get:
      # This script is executed whenever the request is serviced.
      # The last variable is the response object.
      x-sim-script: |
       response = {
          "status": status,
          "headers": {
            "Teapot": "true"
          },
          "body": { "message": "I'm a teapot" }
        }
      responses:
        '200':
          description: OK
