name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u kitproj --password-stdin

      - name: Build and push Docker image
        run:
          docker build . --tag ghcr.io/kitproj/sim:latest
          docker push ghcr.io/kitproj/sim:latest